export const Users = [
    {
      id:1,
      profilePicture: "assets/profile/temi.jpeg",
      username: "Temi Turner",
    },
    {
      id:2,
      profilePicture: "assets/profile/dani.JPG",
      username: "Samuel Daniel",
    },
    {
      id:3,
      profilePicture: "assets/profile/Okiki.jpeg",
      username: "Okiki Onanibosi",
    },
    {
      id:4,
      profilePicture: "assets/profile/prec.jpeg",
      username: "Precious Yusuf",
    },
    {
      id:5,
      profilePicture: "assets/profile/profile1.jpeg",
      username: "David Idowu",
    },
    {
      id:6,
      profilePicture: "assets/profile/profile2.jpg",
      username: "Tobi Kayode",
    },
    {
      id:7,
      profilePicture: "assets/profile/profile3.jpeg",
      username: "Mololuwa Idowu",
    },
    {
      id:8,
      profilePicture: "assets/profile/profile4.jpg",
      username: "Segun Tobi",
    },
    {
      id:9,
      profilePicture: "assets/profile/profile5.jpeg",
      username: "David Kayode",
    },
    {
      id:10,
      profilePicture: "assets/profile/profile6.jpeg",
      username: "Mololuwa David",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Welcome",
      photo: "assets/posts/post1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/posts/post2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "I love this picture so much",
      photo: "assets/posts/post3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/post4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/post5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/post6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Amazing landcsape",
      photo: "assets/posts/post7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/posts/post8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Lionel Messi is the GOAT",
      photo: "assets/posts/post9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/posts/post10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];